# Generated by Django 5.2.5 on 2025-09-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_publication_file_alter_publication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='user',
        ),
    ]
