# Generated by Django 5.2.5 on 2025-09-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_publication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.ImageField(null=True, upload_to='videos/poste'),
        ),
    ]
